"""This module provides an enum with the event types for the communication queue."""

from enum import Enum


class CommunicationEventType(Enum):
    """Event types used in the shared communication queue."""

    VISUALIZATION_START = "VISUALIZATION_START"
    VISUALIZATION_STOP = "VISUALIZATION_STOP"
    LOAD_POINT_CLOUD_FROM_PATH = "LOAD_POINT_CLOUD_FROM_PATH"
    TOGGLE_CAMERA = "TOGGLE_CAMERA"
    ROTATE = "ROTATE"
    ZOOM = "ZOOM"
    SET_DEMO_MODE = "SET_DEMO_MODE"
    SET_TIME_TRAVEL = "SET_TIME_TRAVEL"
    UPDATE_TRANSITION_DELAY = "UPDATE_TRANSITION_DELAY"
    UPDATE_TRANSITION_DURATION = "UPDATE_TRANSITION_DURATION"
    TOGGLE_SEGMENTATION_COLOR = "TOGGLE_SEGMENTATION_COLOR"
    SELECT_DAY = "SELECT_DAY"
    UPDATE_DAY = "UPDATE_DAY"
    GENERATE_NEW_SEGMENTATION_COLOR_SET = "GENERATE_NEW_SEGMENTATION_COLOR_SET"
    SHOW_CAMERA_RENDERER = "SHOW_CAMERA_RENDERER"
    TOGGLE_INFORMATION_OVERLAY = "TOGGLE_INFORMATION_OVERLAY"
    SOUND_ROTATION_POS = "SOUND_ROTATION_POS"
    SOUND_ZOOM_POS = "SOUND_ZOOM_POS"


class CommunicationTargets(Enum):
    """Communication targets to define the receiver for a message."""

    CONTROLLER = "CONTROLLER"
    TRANSITION_CONTROLLER = "TRANSITION_CONTROLLER"
